objects/Account.object
<CustomObject>
    <fields>
        <fullName>Custom_Request_Types__c</fullName>
        <label>Custom Request Types</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inactive_Custom_Request_Types__c</fullName>
        <label>Inactive_Custom_Request_Types</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Winery_Account</fullName>
        <active>true</active>
        <description>Used for Wineries</description>
        <label>Winery Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Tour_and_Tasting_Request__c.object
<CustomObject>
    <fields>
        <fullName>Earliest_Date_of_Visit__c</fullName>
        <inlineHelpText>Enter the earliest date the guest is available for a visit.</inlineHelpText>
        <label>Earliest Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Time__c</fullName>
        <inlineHelpText>Enter the earliest time the guest could arrive for the visit.</inlineHelpText>
        <label>Earliest Start Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>10:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>12:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>12:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:30 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>4:30 PM PDT</label>
                </value>
                <value>
                    <fullName>5:00 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>5:00 PM PDT</label>
                </value>
                <value>
                    <fullName>8:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:00 AM PDT</label>
                </value>
                <value>
                    <fullName>8:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:30 AM PDT</label>
                </value>
                <value>
                    <fullName>9:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:00 AM PDT</label>
                </value>
                <value>
                    <fullName>9:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:30 AM PDT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Latest_Date_of_Visit__c</fullName>
        <inlineHelpText>Latest date the guest is available for a visit.</inlineHelpText>
        <label>Latest Date of Visit</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Start_Time__c</fullName>
        <inlineHelpText>Enter the latest that the guest can start the visit.</inlineHelpText>
        <label>Latest Start Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>10:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>12:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>12:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:30 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>4:30 PM PDT</label>
                </value>
                <value>
                    <fullName>5:00 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>5:00 PM PDT</label>
                </value>
                <value>
                    <fullName>8:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:00 AM PDT</label>
                </value>
                <value>
                    <fullName>8:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:30 AM PDT</label>
                </value>
                <value>
                    <fullName>9:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:00 AM PDT</label>
                </value>
                <value>
                    <fullName>9:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:30 AM PDT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Guests__c</fullName>
        <description>The total number of guests attending.</description>
        <formula>Tour_and_Tasting__r.Number_of_Guests__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of guests attending.</inlineHelpText>
        <label>Number of Guests</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Please select a WINERY first! Then chose your Request Type for the event you wish to set up for your guest.</inlineHelpText>
        <label>xx_Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>T_T_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_text__c</fullName>
        <label>Request Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tour_and_Tasting__c</fullName>
        <label>Tour and Tasting</label>
        <referenceTo>Tours_and_Tastings__c</referenceTo>
        <relationshipLabel>Tour and Tasting Requests</relationshipLabel>
        <relationshipName>Tour_and_Tasting_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Winery__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Winery</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Winery Accounts</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Winery Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tour and Tasting Requests</relationshipLabel>
        <relationshipName>Tour_and_Tasting_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tour and Tasting Request</label>
    <nameField>
        <displayFormat>TTR-{0}</displayFormat>
        <label>Tour and Tasting Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour and Tasting Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tours_and_Tastings__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Guests__c</fullName>
        <inlineHelpText>Number of Total Guest including Primary</inlineHelpText>
        <label>Number of Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>This is the type of person who is requesting a visit to the winery (ie. Distributor, Retailer, Consumer, etc.)</description>
        <inlineHelpText>This is the type of person who is requesting a visit to the winery (ie. Distributor, Retailer, Consumer, etc.)</inlineHelpText>
        <label>Primary Guest Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distributor or Employee</fullName>
                </value>
                <value>
                    <fullName>Family and VIPs</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                    <label>On-Prem Retailer</label>
                </value>
                <value>
                    <fullName>Off-Prem Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Winery__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Winery Account</description>
        <label>Winery</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Winery Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Winery Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tours and Tastings Forms</relationshipLabel>
        <relationshipName>Tours_and_Tastings_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tour and Tasting Form</label>
    <nameField>
        <displayFormat>TT-{0}</displayFormat>
        <label>TT Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours and Tastings Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/T_T_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Tasting</fullName>
        <default>true</default>
        <label>Tasting</label>
    </customValue>
    <customValue>
        <fullName>Tour</fullName>
    </customValue>
    <customValue>
        <fullName>Tour and Tasting</fullName>
    </customValue>
    <masterLabel>T&amp;T Request Type</masterLabel>
</GlobalValueSet>

classes/CustomRequestTypesControllerTest.cls
@isTest
public class CustomRequestTypesControllerTest {
	static testMethod void testMethod1() 
	{
		Account testAccount = new Account();
		testAccount.Name='Test Account' ;
        testAccount.Inactive_Custom_Request_Types__c='test1';
        testAccount.Custom_Request_Types__c='test2';
		insert testAccount;
		
        List <String> options = new  List <String>();
        options.add('test');
		
		Test.StartTest(); 

			string s = CustomRequestTypesController.getOptions(String.valueOf( testAccount.Id));
        	s = CustomRequestTypesController.getInactiveOptions(String.valueOf( testAccount.Id));
			CustomRequestTypesController.setOptions (testAccount.Id,options);
        	system.debug(CustomRequestTypesController.UserHasAccess());

		Test.StopTest();
	}
    static testMethod void testMethod2() 
	{
        Id wineryRecType = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Winery_Account').getRecordTypeId();

        
		Account testAccount = new Account();
		testAccount.Name='Test Account';
        testAccount.RecordTypeId= wineryRecType;
		insert testAccount;
        
        Tours_and_Tastings__c tt = new Tours_and_Tastings__c ();
        tt.Number_of_Guests__c=2;
        tt.Request_Type__c='Retailer';
            
        insert tt;
        
        Tour_and_Tasting_Request__c ttr = new Tour_and_Tasting_Request__c();
        ttr.Winery__c = testAccount.Id;
        ttr.Tour_and_Tasting__c=tt.Id;
        ttr.Earliest_Start_Time__c='10:00 AM PDT';
        ttr.Latest_Start_Time__c='11:00 AM PDT';
        ttr.Earliest_Date_of_Visit__c=System.today() + 10;
        ttr.Latest_Date_of_Visit__c=System.today() + 20;
        ttr.Request_Type_text__c = 'Retailer';
        insert ttr;
        system.debug(ttr.Id);
		
        List <String> options = new  List <String>();
        options.add('test');
		
		Test.StartTest(); 
			TTCustomRequestTypeController.setOptions (ttr.Id,'test');
			List <string> s = TTCustomRequestTypeController.getOptions(String.valueOf( ttr.Id));
			
        	
        
			testAccount.Custom_Request_Types__c='';
			update testAccount; 
        	TTCustomRequestTypeController.setOptions (ttr.Id,'test');
        	s = TTCustomRequestTypeController.getOptions(String.valueOf( ttr.Id));

		Test.StopTest();
	}
    static testMethod void testMethod3() 
	{
        Id wineryRecType = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Winery_Account').getRecordTypeId();

        
		Account testAccount = new Account();
		testAccount.Name='Test Account';
        testAccount.RecordTypeId= wineryRecType;
		insert testAccount;
        
        Tours_and_Tastings__c tt = new Tours_and_Tastings__c ();
        tt.Number_of_Guests__c=2;
        tt.Request_Type__c='Retailer';
        insert tt;
        
        Tour_and_Tasting_Request__c ttr = new Tour_and_Tasting_Request__c();
        ttr.Winery__c = testAccount.Id;
        ttr.Tour_and_Tasting__c=tt.Id;
        ttr.Earliest_Start_Time__c='10:00 AM PDT';
        ttr.Latest_Start_Time__c='11:00 AM PDT';
        ttr.Earliest_Date_of_Visit__c=System.today() + 10;
        ttr.Latest_Date_of_Visit__c=System.today() + 20;
        ttr.Request_Type_text__c='Retailer';
        
        //insert ttr;
		
		Test.StartTest(); 

			String s  = CustomTTRCreate.getOptions(String.valueOf( testAccount.Id));
        	
			s = CustomTTRCreate.saveRecordContr (JSON.serialize(ttr));
		Test.StopTest();
	}
    
}