objects/Account.object
<CustomObject>
    <fields>
        <fullName>Private_Tours__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used on the Winery account page to display if the winery provides tours of their facilities.</description>
        <inlineHelpText>Checkbox displays if the winery provides tours of their facilities.</inlineHelpText>
        <label>Tours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tours_Tastings_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines whether or not the Tours &amp; Tastings App can create a T&amp;T Request for this winery. Checked allows requests, Unchecked does not allow requests; based on validation rule on the TTR.</description>
        <inlineHelpText>This field determines whether or not the Tours &amp; Tastings App can create a T&amp;T Request for this winery. Checked allows requests; Unchecked does not allow requests.</inlineHelpText>
        <label>Tours &amp; Tastings Accepted</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Retailer_Account</fullName>
        <active>true</active>
        <description>Retailer of items sold by Terlato</description>
        <label>Retailer Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Winery_Account</fullName>
        <active>true</active>
        <description>Used for Wineries</description>
        <label>Winery Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Tour_and_Tasting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour and Tasting</label>
        <referenceTo>Tours_and_Tastings__c</referenceTo>
        <relationshipLabel>Tour and Tasting Guests</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tour_and_Tasting_Request__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_Date_of_Visit__c</fullName>
        <description>Field is only populated by the winery and/or Leah/Carla</description>
        <label>Confirmed Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Date_of_Visit__c</fullName>
        <inlineHelpText>Enter the earliest date the guest is available for a visit.</inlineHelpText>
        <label>Earliest Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Time__c</fullName>
        <inlineHelpText>Enter the earliest time the guest could arrive for the visit.</inlineHelpText>
        <label>Earliest Start Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>10:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>12:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>12:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:30 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>4:30 PM PDT</label>
                </value>
                <value>
                    <fullName>5:00 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>5:00 PM PDT</label>
                </value>
                <value>
                    <fullName>8:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:00 AM PDT</label>
                </value>
                <value>
                    <fullName>8:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:30 AM PDT</label>
                </value>
                <value>
                    <fullName>9:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:00 AM PDT</label>
                </value>
                <value>
                    <fullName>9:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:30 AM PDT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Latest_Date_of_Visit__c</fullName>
        <inlineHelpText>Latest date the guest is available for a visit.</inlineHelpText>
        <label>Latest Date of Visit</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Start_Time__c</fullName>
        <inlineHelpText>Enter the latest that the guest can start the visit.</inlineHelpText>
        <label>Latest Start Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>10:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:00 AM PDT</fullName>
                </value>
                <value>
                    <fullName>11:30 AM PDT</fullName>
                </value>
                <value>
                    <fullName>12:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>12:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>1:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>2:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>3:30 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:00 PM PDT</fullName>
                </value>
                <value>
                    <fullName>4:30 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>4:30 PM PDT</label>
                </value>
                <value>
                    <fullName>5:00 PM PDT</fullName>
                    <isActive>false</isActive>
                    <label>5:00 PM PDT</label>
                </value>
                <value>
                    <fullName>8:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:00 AM PDT</label>
                </value>
                <value>
                    <fullName>8:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>8:30 AM PDT</label>
                </value>
                <value>
                    <fullName>9:00 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:00 AM PDT</label>
                </value>
                <value>
                    <fullName>9:30 AM PDT</fullName>
                    <isActive>false</isActive>
                    <label>9:30 AM PDT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Guests__c</fullName>
        <description>The total number of guests attending.</description>
        <formula>Tour_and_Tasting__r.Number_of_Guests__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of guests attending.</inlineHelpText>
        <label>Number of Guests</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Guest_Name__c</fullName>
        <formula>Tour_and_Tasting__r.Primary_Guest_Name__r.FirstName &amp; &apos; &apos; &amp; Tour_and_Tasting__r.Primary_Guest_Name__r.LastName</formula>
        <label>Primary Guest Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Please select a WINERY first! Then chose your Request Type for the event you wish to set up for your guest.</inlineHelpText>
        <label>xx_Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>T_T_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_text__c</fullName>
        <label>Request Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tour_and_Tasting__c</fullName>
        <label>Tour and Tasting</label>
        <referenceTo>Tours_and_Tastings__c</referenceTo>
        <relationshipLabel>Tour and Tasting Requests</relationshipLabel>
        <relationshipName>Tour_and_Tasting_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Winery__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Winery</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Winery Accounts</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Winery Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tour and Tasting Requests</relationshipLabel>
        <relationshipName>Tour_and_Tasting_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tour and Tasting Request</label>
    <nameField>
        <displayFormat>TTR-{0}</displayFormat>
        <label>Tour and Tasting Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour and Tasting Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tours_and_Tastings__c.object
<CustomObject>
    <fields>
        <fullName>Level_of_Wine_Knowledge__c</fullName>
        <label>Level of Wine Knowledge</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Fair</fullName>
                </value>
                <value>
                    <fullName>Novice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Guests__c</fullName>
        <inlineHelpText>Number of Total Guest including Primary</inlineHelpText>
        <label>Number of Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Guest_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Guest Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours and Tastings</relationshipLabel>
        <relationshipName>Tours_and_Tastings_Consumer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>This is the type of person who is requesting a visit to the winery (ie. Distributor, Retailer, Consumer, etc.)</description>
        <inlineHelpText>This is the type of person who is requesting a visit to the winery (ie. Distributor, Retailer, Consumer, etc.)</inlineHelpText>
        <label>Primary Guest Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distributor or Employee</fullName>
                </value>
                <value>
                    <fullName>Family and VIPs</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                    <label>On-Prem Retailer</label>
                </value>
                <value>
                    <fullName>Off-Prem Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Winery__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Winery Account</description>
        <label>Winery</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Winery Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Winery Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tours and Tastings Forms</relationshipLabel>
        <relationshipName>Tours_and_Tastings_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tour and Tasting Form</label>
    <nameField>
        <displayFormat>TT-{0}</displayFormat>
        <label>TT Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours and Tastings Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/T_T_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Tasting</fullName>
        <default>true</default>
        <label>Tasting</label>
    </customValue>
    <customValue>
        <fullName>Tour</fullName>
    </customValue>
    <customValue>
        <fullName>Tour and Tasting</fullName>
    </customValue>
    <masterLabel>T&amp;T Request Type</masterLabel>
</GlobalValueSet>

classes/ToursTastingsFormApprovalControllerTest.cls
/**
 * Created by cyoungmark on 2019-07-24.
 */

@IsTest
private class ToursTastingsFormApprovalControllerTest {

    @testSetup
    private static void generateData() {

        // TODO: Create Winery Account
        Account wineryAccount = new Account(

                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Winery_Account').getRecordTypeId(),
                Name = 'Test Winery',
                Tours_Tastings_Accepted__c = true,
                Private_Tours__c = true

        );

        insert wineryAccount;

        // TODO: Create Retailer Account
        Account retailerAccount = new Account(

                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Retailer_Account').getRecordTypeId(),
                Name = 'Test Retailer'

        );

        insert retailerAccount;

        // TODO: Create Primary Contact
        Contact primaryContact = new Contact(

                AccountId = retailerAccount.Id,
                FirstName = 'Test',
                LastName = 'Guest',
                Email = 'test@test.com',
                MobilePhone = '312-588-2300'

        );

        // TODO: Create Tour and Tastings Form

        Tours_and_Tastings__c theForm = new Tours_and_Tastings__c(

                Request_Type__c = 'Consumer',
                Primary_Guest_Name__c = primaryContact.Id,
                Number_of_Guests__c = 1,
                Level_of_Wine_Knowledge__c = 'High'
            	

        );

        insert theForm;
        
        Tours_and_Tastings__c theForm2 = new Tours_and_Tastings__c(

                Request_Type__c = 'Consumer',
                Primary_Guest_Name__c = primaryContact.Id,
                Number_of_Guests__c = 1,
                Level_of_Wine_Knowledge__c = 'Novice'
            	

        );

		insert theForm2;
        // TODO: Create Tour and Tastings Request

        Tour_and_Tasting_Request__c theRequestForApproval = new Tour_and_Tasting_Request__c(

                Tour_and_Tasting__c = theForm.Id,
                Winery__c = wineryAccount.Id,
                Earliest_Date_of_Visit__c = Date.Today() + 14,
                Earliest_Start_Time__c = '10:00 AM PDT',
                Latest_Date_of_Visit__c = Date.Today() + 21,
                Latest_Start_Time__c = '11:00 AM PDT',
                Request_Type__c = 'Tour',
                Request_Type_text__c = 'Tour',
            	Confirmed_Date_Of_Visit__c = Date.today() + 14,
            	Confirmed_Time_Of_Visit__c = '10:00 AM PDT',
            	Itinerary_Recipient_Email__c = 'Test@test.com'

        );

        insert theRequestForApproval;

        Tour_and_Tasting_Request__c theRequestWithoutApproval = new Tour_and_Tasting_Request__c(

                Tour_and_Tasting__c = theForm.Id,
                Winery__c = wineryAccount.Id,
                Earliest_Date_of_Visit__c = Date.Today() + 14,
                Earliest_Start_Time__c = '10:00 AM PDT',
                Latest_Date_of_Visit__c = Date.Today() + 21,
                Latest_Start_Time__c = '11:00 AM PDT',
                Request_Type__c = 'Tasting',
                Request_Type_text__c = 'Tasting',
            	Confirmed_Date_Of_Visit__c = Date.today() + 14,
            	Confirmed_Time_Of_Visit__c = '10:00 AM PDT',
            	Itinerary_Recipient_Email__c = 'Test@test.com'

        );

        insert theRequestWithoutApproval;

        // TODO: Submit approval request

        Approval.ProcessSubmitRequest theApproval = new Approval.ProcessSubmitRequest();

        theApproval.setComments('Please approve this request.');
        theApproval.setObjectId(theForm.id);

        Approval.ProcessResult theApprovalResult = Approval.process(theApproval);

    }

    @isTest
    private static void testGetProcessInstance() {

        // Retrieve the Request so that you can use its Id

        Tours_and_Tastings__c theRequestWithApproval = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'High' LIMIT 1];
        Tours_and_Tastings__c theRequestWithoutApproval = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'Novice' LIMIT 1];

        Test.StartTest();

        //Happy Path: Approval Request was submitted
        ProcessInstance theProcessInstanceHappyPath = ToursTastingsFormApprovalController.getProcessInstance(theRequestWithApproval.Id);

        //Alternative Path: Approval Request wasn't submitted
        ProcessInstance theProcessInstanceAlternativePath = ToursTastingsFormApprovalController.getProcessInstance(theRequestWithoutApproval.Id);

        Test.StopTest();

        System.AssertEquals('Pending', theProcessInstanceHappyPath.Status, 'Happy path: Process Instance status is wrong!');
        System.AssertEquals(null, theProcessInstanceAlternativePath, 'Alternative path: Process Instance must be null');
    }

    @isTest
    private static void testGetProcessInstanceWorkitem() {

        // Retrieve the Request so that you can use its Id

        Tours_and_Tastings__c theRequestWithApproval = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'High' LIMIT 1];
        Tours_and_Tastings__c theRequestWithoutApproval = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'Novice' LIMIT 1];

        Test.StartTest();

        //Happy Path: Approval Request was submitted
        ProcessInstanceWorkitem theProcessInstanceWorkItemHappyPath = ToursTastingsFormApprovalController.getProcessInstanceWorkitem(theRequestWithApproval.Id);

        //Alternative Path: Approval Request wasn't submitted
        ProcessInstanceWorkitem theProcessInstanceWorkItemAlternativePath = ToursTastingsFormApprovalController.getProcessInstanceWorkitem(theRequestWithoutApproval.Id);

        Test.StopTest();

        System.AssertNotEquals(null, theProcessInstanceWorkItemHappyPath, 'Happy Path: Process Instance Work Item cannot be null');
        System.AssertEquals(null, theProcessInstanceWorkItemAlternativePath, 'Alternative Path: Process Instance Work Item must be null');
    }

    @isTest
    private static void testGetProcessInstanceHistory() {

        // Retrieve the Request so that you can use its Id

        Tours_and_Tastings__c theRequestWithApproval = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'High' LIMIT 1];
        Tours_and_Tastings__c theRequestWithoutApproval = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'Novice' LIMIT 1];

        Test.StartTest();

        //Happy Path: Approval Request was submitted
        ProcessInstanceHistory theProcessInstanceHistoryHappyPath = ToursTastingsFormApprovalController.getLatestHistory(theRequestWithApproval.Id);

        //Alternative Path: Approval Request wasn't submitted
        ProcessInstanceHistory theProcessInstanceHistoryAlternativePath = ToursTastingsFormApprovalController.getLatestHistory(theRequestWithoutApproval.Id);

        Test.StopTest();

        System.AssertNotEquals(null, theProcessInstanceHistoryHappyPath, 'Happy Path: Process Instance History cannot be null');
        System.AssertEquals(null, theProcessInstanceHistoryAlternativePath, 'Alternative Path: Process Instance History must be null');

    }

    @isTest
    private static void testIsApprover() {

        // Retrieve the Request so that you can use its Id

        Tours_and_Tastings__c theRequest = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'High' LIMIT 1];

        Test.StartTest();

        Boolean isApprover = ToursTastingsFormApprovalController.isApprover(theRequest.Id);

        Test.StopTest();

    }

    @isTest
    private static void testRunningUser() {

        Test.StartTest();

        User runningUser = ToursTastingsFormApprovalController.getRunningUser();

        Test.StopTest();

        System.AssertEquals(userInfo.getUserId(), runningUser.Id);

    }

    @isTest
    private static void testSubmitApproval() {

        // Retrieve the Request so that you can use its Id

		Tours_and_Tastings__c theRequest = [SELECT Id FROM Tours_and_Tastings__c WHERE Request_Type__c = 'Consumer' AND Level_of_Wine_Knowledge__c = 'High' LIMIT 1];        

        Test.StartTest();

        Boolean isSuccess = ToursTastingsFormApprovalController.submitApproval(theRequest.Id, 'Approve', 'Test approval comments.');

        Test.StopTest();

        System.Assert(isSuccess);

    }


}