objects/Account.object
<CustomObject>
    <fields>
        <fullName>Custom_Request_Types__c</fullName>
        <label>Custom Request Types</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Tour_and_Tasting_Request__c.object
<CustomObject>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Please select a WINERY first! Then chose your Request Type for the event you wish to set up for your guest.</inlineHelpText>
        <label>xx_Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>T_T_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type_text__c</fullName>
        <label>Request Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winery__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Winery</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Winery Accounts</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Winery Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tour and Tasting Requests</relationshipLabel>
        <relationshipName>Tour_and_Tasting_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Tour and Tasting Request</label>
    <nameField>
        <displayFormat>TTR-{0}</displayFormat>
        <label>Tour and Tasting Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour and Tasting Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/T_T_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Tasting</fullName>
        <default>true</default>
        <label>Tasting</label>
    </customValue>
    <customValue>
        <fullName>Tour</fullName>
    </customValue>
    <customValue>
        <fullName>Tour and Tasting</fullName>
    </customValue>
    <masterLabel>T&amp;T Request Type</masterLabel>
</GlobalValueSet>

classes/TTCustomRequestTypeController.cls
public class TTCustomRequestTypeController {
 	@AuraEnabled
     public static List <String> getOptions(String TTId){
    	 Tour_and_Tasting_Request__c tt = [select Winery__r.Custom_Request_Types__c,Request_Type_text__c,Request_Type__c from Tour_and_Tasting_Request__c where id =:TTId];
         List <String> ret = new List <String>();
         if (tt.Winery__r.Custom_Request_Types__c!=null && tt.Winery__r.Custom_Request_Types__c != ''){
             ret.add(tt.Winery__r.Custom_Request_Types__c);
             ret.add(tt.Request_Type_text__c);
         } else {
             Schema.DescribeFieldResult fieldResult = Tour_and_Tasting_Request__c.Request_Type__c.getDescribe();
             List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
             String picklistValues = '';
             for( Schema.PicklistEntry pickListVal : ple){
                 picklistValues += pickListVal.getValue() + '|';
             } 
             ret.add(picklistValues.removeEnd('|'));
             
             if (tt.Request_Type_text__c!=null && tt.Request_Type_text__c!=''){
                 ret.add(tt.Request_Type_text__c);
             } else {
             	ret.add(tt.Request_Type__c);
             }

         } 
            
         
         
         return ret;
     }
    @AuraEnabled
     public static String setOptions(String TTId, String options){
         try{
             Tour_and_Tasting_Request__c tt = [select Id, Request_Type_text__c from Tour_and_Tasting_Request__c where id =:TTId];
             tt.Request_Type_text__c = options;
             update tt;
             return 'Success';
         } catch (DmlException e){
             system.debug(e.getMessage());
             throw new AuraHandledException(e.getMessage());
         }
         
     }
    
}