objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Code_Marketing__c</fullName>
        <description>Brand Code is a 3 character code that represents a brand. (i.e., &quot;Gaja&quot; brand has code of &quot;GAJ&quot;). The Brand Code is created by accounting if one does not exist.</description>
        <externalId>true</externalId>
        <inlineHelpText>Brand Code is a 3 character code that represents a brand. (i.e., &quot;Gaja&quot; brand has code of &quot;GAJ&quot;). The Brand Code is created by accounting if one does not exist.</inlineHelpText>
        <label>Brand Code (Marketing)</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Marketing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Marketing Executive in charge of this brand.</description>
        <inlineHelpText>The Marketing Executive in charge of this brand.</inlineHelpText>
        <label>Marketing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Marketing Manager that is managing this brand.</description>
        <label>Marketing Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Marketing_Manager_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name (Marketing)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Product_Description__c</fullName>
        <label>Marketing Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Product_Name__c</fullName>
        <description>Product name only, without brand or vintage information</description>
        <inlineHelpText>The &quot;name&quot; of the product only, WITHOUT the Brand name or varietal. For example, Chimney Rock Tomahawk Vineyard Cabernet 2013, the name would be &quot;Tomahawk Vineyard&quot;.</inlineHelpText>
        <label>Marketing Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vintage__c</fullName>
        <label>Vintage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                    <label>2018</label>
                </value>
                <value>
                    <fullName>217</fullName>
                    <label>2017</label>
                </value>
                <value>
                    <fullName>216</fullName>
                    <label>2016</label>
                </value>
                <value>
                    <fullName>215</fullName>
                    <label>2015</label>
                </value>
                <value>
                    <fullName>214</fullName>
                    <label>2014</label>
                </value>
                <value>
                    <fullName>213</fullName>
                    <label>2013</label>
                </value>
                <value>
                    <fullName>212</fullName>
                    <label>2012</label>
                </value>
                <value>
                    <fullName>211</fullName>
                    <label>2011</label>
                </value>
                <value>
                    <fullName>210</fullName>
                    <label>2010</label>
                </value>
                <value>
                    <fullName>209</fullName>
                    <label>2009</label>
                </value>
                <value>
                    <fullName>208</fullName>
                    <label>2008</label>
                </value>
                <value>
                    <fullName>207</fullName>
                    <label>2007</label>
                </value>
                <value>
                    <fullName>206</fullName>
                    <label>2006</label>
                </value>
                <value>
                    <fullName>205</fullName>
                    <label>2005</label>
                </value>
                <value>
                    <fullName>204</fullName>
                    <label>2004</label>
                </value>
                <value>
                    <fullName>203</fullName>
                    <label>2003</label>
                </value>
                <value>
                    <fullName>202</fullName>
                    <label>2002</label>
                </value>
                <value>
                    <fullName>201</fullName>
                    <label>2001</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <label>2000</label>
                </value>
                <value>
                    <fullName>199</fullName>
                    <label>1999</label>
                </value>
                <value>
                    <fullName>198</fullName>
                    <label>1998</label>
                </value>
                <value>
                    <fullName>197</fullName>
                    <label>1997</label>
                </value>
                <value>
                    <fullName>196</fullName>
                    <label>1996</label>
                </value>
                <value>
                    <fullName>195</fullName>
                    <label>1995</label>
                </value>
                <value>
                    <fullName>194</fullName>
                    <label>1994</label>
                </value>
                <value>
                    <fullName>193</fullName>
                    <label>1993</label>
                </value>
                <value>
                    <fullName>192</fullName>
                    <label>1992</label>
                </value>
                <value>
                    <fullName>191</fullName>
                    <label>1991</label>
                </value>
                <value>
                    <fullName>190</fullName>
                    <label>1990</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item - Active</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items - Active</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SetItemNameTest.cls
@isTest(SeeAllData=true)
public with sharing class SetItemNameTest{

    public static testMethod void test() {
        Brand__c b = new Brand__c ();
        b.name ='test';
        b.Brand_Code_Marketing__c='123';
        User u = [Select Id from User where isActive=true limit 1];
        b.Marketing_Executive__c=u.id;
        b.Marketing_Manager__c=u.id;
        insert b;
        
        Item__c i = new Item__c();
        i.name='test';
        i.Marketing_Product_Name__c='test';
        i.Marketing_Product_Description__c='test';
        i.Brand__c=b.Id;
        i.Vintage__c='210';
        insert i;
        
        Item__c item = [select name from Item__c where Id=: i.Id];
        //system.AssertEquals (item.name,'test-2010-test');
        
      }
  }