objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Marketing Manager that is managing this brand.</description>
        <label>Marketing Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Marketing_Manager_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name (Marketing)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Brand_trigger_statuses__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Brand trigger statuses</label>
</CustomObject>

objects/Item_Update__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>IIP: Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Approvals</fullName>
                </value>
                <value>
                    <fullName>Approvals Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed - Record Locked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>IIP: Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Item_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item - In Process</label>
    <nameField>
        <displayFormat>IIP-{0}</displayFormat>
        <label>IIP No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items - In Process</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_Brand_Trigger_Handler.cls
@isTest
private class Test_Brand_Trigger_Handler {
	
	@isTest static void test_method_one() {

		Brand_trigger_statuses__c customSetting = new Brand_trigger_statuses__c();
		customSetting.Name = 'In Progress';
		insert customSetting;
		
		Brand__c brand = UtilitiesForTestMethodsClass.getBrand();

		Item_Update__c itemUpdate = UtilitiesForTestMethodsClass.getItemUpdate('Item Update (Copy)', UtilitiesForTestMethodsClass.getItemNew().Id);
		itemUpdate.Brand__c = brand.Id;
		itemUpdate.Approval_Status__c = 'In Progress';
		insert itemUpdate;

		brand.Marketing_Manager__c = UtilitiesForTestMethodsClass.getUser('silverlinesucks@neverhireusagain.com').Id;
		update brand;
	}

}