objects/Fields_Item_Update_Copy_A__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IA TO IIP (A)</description>
    <fields>
        <fullName>Item_In_Process_field_API_name__c</fullName>
        <label>Item In Process field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: Item Update (Copy) A</label>
</CustomObject>

objects/Fields_Item_Update_Copy_B__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IIP TO IA (B)</description>
    <fields>
        <fullName>Item_Active_field_API_name__c</fullName>
        <label>Item Active field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: Item Update (Copy) B</label>
</CustomObject>

objects/Fields_New_Item_Vintage_Copy_A__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IA TO IIP (A)</description>
    <fields>
        <fullName>Item_In_Process_field_API_name__c</fullName>
        <label>Item In Process field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: New Item/Vintage (Copy) A</label>
</CustomObject>

objects/Fields_New_Item_Vintage_Copy_B__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IIP TO IA (B)</description>
    <fields>
        <fullName>Item_Active_field_API_name__c</fullName>
        <label>Item Active field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: New Item/Vintage (Copy) B</label>
</CustomObject>

objects/Fields_State_pricing_A__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IA TO IIP (A)</description>
    <fields>
        <fullName>Target_field_API_name__c</fullName>
        <label>Target field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: State pricing A</label>
</CustomObject>

objects/Fields_State_pricing_B__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IIP TO IA (B)</description>
    <fields>
        <fullName>Target_field_API_name__c</fullName>
        <label>Target field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: State pricing B</label>
</CustomObject>

objects/Fields_Winery_Unfinished_Item_Copy_A__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>MAPPING FROM IA TO IIP (A)</description>
    <fields>
        <fullName>Item_In_Process_field_API_name__c</fullName>
        <label>Item In Process field API name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Fields: Winery Unfinished Item (Copy) A</label>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Add_State_Adjustment__c</fullName>
        <label>Add_State_Adjustment</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aging__c</fullName>
        <label>Aging</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Base_Units_per_Case__c</fullName>
        <label>Base Units per Case</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Base_Units_per_Case</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IU_Type__c</fullName>
        <label>XXIU Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Item</fullName>
                </value>
                <value>
                    <fullName>New Item / Vintage (Copy)</fullName>
                </value>
                <value>
                    <fullName>Item Update (Copy)</fullName>
                </value>
                <value>
                    <fullName>Winery Unfinished Item</fullName>
                </value>
                <value>
                    <fullName>Winery Unfinished Item (Copy)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Product_Name__c</fullName>
        <description>Product name only, without brand or vintage information</description>
        <inlineHelpText>The &quot;name&quot; of the product only, WITHOUT the Brand name or varietal. For example, Chimney Rock Tomahawk Vineyard Cabernet 2013, the name would be &quot;Tomahawk Vineyard&quot;.</inlineHelpText>
        <label>Marketing Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Item - Active</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items - Active</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Item_Update__c.object
<CustomObject>
    <fields>
        <fullName>Add_State_Adjustment__c</fullName>
        <label>IIP: Add_State_Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Aging__c</fullName>
        <label>IIP: Aging</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Base_Units_per_Case__c</fullName>
        <description>This is the total number of base units of product per case; even if there are kits or mini packs included. For example, Seven Daughters cans are 8 kits of 4 cans each per case, or 24 base units per case.</description>
        <inlineHelpText>This is the total number of base units of product per case; even if there are kits or mini packs included. For example, Seven Daughters cans are 8 kits of 4 cans each per case, or 24 base units per case.</inlineHelpText>
        <label>IIP: Base Units per Case</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Base_Units_per_Case</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>What item do you want to copy from?</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipName>Item_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Product_Name__c</fullName>
        <description>Product name only, without brand or vintage information</description>
        <inlineHelpText>The &quot;name&quot; of the product only, WITHOUT the Brand name, varietal or vintage year. For example, Chimney Rock Tomahawk Vineyard Cabernet 2013, the name would be &quot;Tomahawk Vineyard&quot;.</inlineHelpText>
        <label>IIP: Marketing Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Item - In Process</label>
    <nameField>
        <displayFormat>IIP-{0}</displayFormat>
        <label>IIP No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items - In Process</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/State_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Item_Update__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item - In Process</label>
        <referenceTo>Item_Update__c</referenceTo>
        <relationshipLabel>State Pricing</relationshipLabel>
        <relationshipName>State_Pricings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item - Active</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>State Pricing</relationshipLabel>
        <relationshipName>State_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Adjustment__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>State Adj</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>State Pricing</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>State Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Pricings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Base_Units_per_Case.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>1 item in the case</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>2 Pack</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>3 Pack</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>4 Pack</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>6 Pack</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12 Pack</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>12 Pack 1.5L</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24 Pack</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>9 Pack</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Pack</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15 Pack</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16 Pack</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 Pack</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>36 Pack</label>
    </customValue>
    <customValue>
        <fullName>48</fullName>
        <label>48 Pack</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60 Pack</label>
    </customValue>
    <customValue>
        <fullName>96</fullName>
        <label>96 Pack</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>120 Pack</label>
    </customValue>
    <masterLabel>Base Units per Case</masterLabel>
</GlobalValueSet>

classes/UtilitiesForTestMethodsClass.cls
/************************************************************************************************************
* Class Name       : UtilitiesForTestMethodsClass
* Version          : 1.0
* Created Date     : 18/01/2017
* Description      : This class helps on test methods creation so that when SFDC model changes the only place
*                  : that needs to be changed is this class instead of every test method
* Modification Log :
* Developer name                 Date                       Description
* ----------------------------------------------------------------------------------------------------------
* Jonathan Major                18/01/2017                Initial version
------------------------------------------------------------------------------------------------------------
************************************************************************************************************/
@isTest
public without sharing class UtilitiesForTestMethodsClass
{
    public static List<sObject> getCustomSetting()
    {   
        List<sObject> listSObjects = new List<sObject>();

        Fields_Item_Update_Copy_A__c setting1 = new Fields_Item_Update_Copy_A__c();
        setting1.Name = 'Aging__c';
        setting1.Item_In_Process_field_API_name__c = 'Aging__c';
        listSObjects.add(setting1);

        Fields_New_Item_Vintage_Copy_A__c setting2 = new Fields_New_Item_Vintage_Copy_A__c();
        setting2.Name = 'Aging__c';
        setting2.Item_In_Process_field_API_name__c = 'Aging__c';
        listSObjects.add(setting2);

        Fields_Winery_Unfinished_Item_Copy_A__c setting3 = new Fields_Winery_Unfinished_Item_Copy_A__c();
        setting3.Name = 'Aging__c';
        setting3.Item_In_Process_field_API_name__c = 'Aging__c';
        listSObjects.add(setting3);

        Fields_State_pricing_A__c setting4 = new Fields_State_pricing_A__c();
        setting4.Name = 'State__c';
        setting4.Target_field_API_name__c   = 'State__c';
        listSObjects.add(setting4);

        Fields_New_Item_Vintage_Copy_B__c setting5 = new Fields_New_Item_Vintage_Copy_B__c();
        setting5.Name = 'Aging__c';
        setting5.Item_Active_field_API_name__c = 'Aging__c';
        listSObjects.add(setting5);

        Fields_State_pricing_B__c  setting6 = new Fields_State_pricing_B__c ();
        setting6.Name = 'State_Adjustment__c';
        setting6.Target_field_API_name__c = 'State_Adjustment__c';
        listSObjects.add(setting6);

        IU_types_to_remove_lookup__c setting7 = new IU_types_to_remove_lookup__c();
        setting7.Name = 'New Item / Vintage (Copy)';
        listSObjects.add(setting7);

        Fields_Item_Update_Copy_B__c  setting8 = new Fields_Item_Update_Copy_B__c();
        setting8.Name = 'Add_State_Adjustment__c';
        setting8.Item_Active_field_API_name__c = 'Add_State_Adjustment__c';
        listSObjects.add(setting8);

        insert listSObjects;

        return listSObjects;
    }

    public static Item__c getItemNew()
    {
        Item__c itemNew = new Item__c(
                Name = 'Item - Active TEST',
                Marketing_Product_Name__c='test',
                Base_Units_per_Case__c = '12');
        insert itemNew;
        return itemNew;
    }

    public static State_Pricing__c getStatePricing(String itemNewId)
    {
        State_Pricing__c statePricing = new State_Pricing__c(Item__c = itemNewId);
        insert statePricing;
        return statePricing;
    }

    public static Item_Update__c getItemUpdate(String ui_type, Id itemNewId)
    {
        Item_Update__c itemUpdate = new Item_Update__c(
                IU_Type__c = ui_type,
                Item__c = itemNewId,
                Base_Units_per_Case__c = '12'
        );
        itemUpdate.Marketing_Product_Name__c='test';
        //insert itemUpdate;
        return itemUpdate;
    }

    public static User getUser(String userName)
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'xyz123', Email='test@test.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName=userName);
        insert u;
        return u;
    }

    public static Item_Files__c getItemFile(Id itemUpdateParent)
    {
        Item_Files__c itemFile = new Item_Files__c(Parent__c = itemUpdateParent, Document_Type__c = 'Other');
        insert itemFile;
        return itemFile;
    }

    public static Brand__c getBrand()
    {
        Brand__c brand = new Brand__c(Name = 'Brand Test', Brand_Code_Marketing__c = 'GAJ', Marketing_Manager__c = getUser('silverlinesucks@neverhireusagain.new').Id, Marketing_Executive__c = getUser('silverlinesucks@neverhireusagain.org').Id);
        insert brand;
        return brand;
    }

    public static HFT__Field_Tracker_Preferences__c getFieldTrackerPreferences()
    {
        HFT__Field_Tracker_Preferences__c fieldTrackerPreferences = new HFT__Field_Tracker_Preferences__c(HFT__Object_Name__c = 'Item_Update__c', HFT__Selected_Fields__c = 'Last Name');
        insert fieldTrackerPreferences;
        return fieldTrackerPreferences;
    }

    public static HFT__Field_Histories__c getFieldHistory()
    {
        Item__c itemNew = getItemNew();
        Item_Update__c itemUpdate = getItemUpdate('Item Update (Copy)', itemNew.Id);
        insert itemUpdate;

        HFT__Field_Histories__c fieldHistory = new HFT__Field_Histories__c(
                                                                              HFT__HFT_Preferences__c = getFieldTrackerPreferences().Id,
                                                                              Item__c = itemNew.Id,
                                                                              Item_Update__c = itemUpdate.Id, 
                                                                              HFT__Object_Name__c = 'Item_Update__c'
                                                                          );
        insert fieldHistory;
        System.debug('fieldHistory: ' + fieldHistory);
        return fieldHistory;
    }
}