objects/Item__c.object
<CustomObject>
    <label>Item - Active</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items - Active</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Item_Update__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>What item do you want to copy from?</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipName>Item_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item - In Process</label>
    <nameField>
        <displayFormat>IIP-{0}</displayFormat>
        <label>IIP No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items - In Process</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/State_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Item_Update__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item - In Process</label>
        <referenceTo>Item_Update__c</referenceTo>
        <relationshipLabel>State Pricing</relationshipLabel>
        <relationshipName>State_Pricings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item - Active</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>State Pricing</relationshipLabel>
        <relationshipName>State_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State Pricing</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>State Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Pricings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DownloadCostFieldsTest.cls
@isTest
private class DownloadCostFieldsTest {
	@isTest static void test_method_one() {
        List<Item_Update__c> listItemUpdate = new List<Item_Update__c>();       

        User brandOwner = UtilitiesForTestMethodsClass.getUser('standarduser_test@silverlinecrm.com.sldev');
        List<sObject> customSettings = UtilitiesForTestMethodsClass.getCustomSetting();
        Item__c itemNew = UtilitiesForTestMethodsClass.getItemNew();
        State_Pricing__c statePricing = UtilitiesForTestMethodsClass.getStatePricing(itemNew.Id);

        Item_Update__c itemUpdate_copy = UtilitiesForTestMethodsClass.getItemUpdate('Item Update (Copy)', itemNew.Id);
        listItemUpdate.add(itemUpdate_copy);
        Item_Update__c itemUpdate_vintage_copy = UtilitiesForTestMethodsClass.getItemUpdate('New Item / Vintage (Copy)', itemNew.Id);
        listItemUpdate.add(itemUpdate_vintage_copy);
        Item_Update__c itemUpdate_unfinishedItem = UtilitiesForTestMethodsClass.getItemUpdate('Winery Unfinished Item (Copy)', itemNew.Id);
        listItemUpdate.add(itemUpdate_unfinishedItem);

        insert listItemUpdate;
        
        string s = DownloadCostFields.getFieldSet('Item_Update__c','Cost_Fields');
        s = DownloadCostFields.getRecords('Item_Update__c','["Id","Name"]');
    }
}