objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Items_Active</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_designation__c</fullName>
        <label>Item designation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Winery only</fullName>
                </value>
                <value>
                    <fullName>Winery &amp; Wholesale</fullName>
                </value>
                <value>
                    <fullName>Wholesale only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item - Active</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items - Active</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Item_Files__c.object
<CustomObject>
    <label>Item Files</label>
    <nameField>
        <displayFormat>IFN{0}</displayFormat>
        <label>Item File No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Update__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>IIP: Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Approvals</fullName>
                </value>
                <value>
                    <fullName>Approvals Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed - Record Locked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IIP: Brand VP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Item_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>What item do you want to copy from?</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipName>Item_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_designation__c</fullName>
        <label>IIP: Item designation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Winery only</fullName>
                </value>
                <value>
                    <fullName>Winery &amp; Wholesale</fullName>
                </value>
                <value>
                    <fullName>Wholesale only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item - In Process</label>
    <nameField>
        <displayFormat>IIP-{0}</displayFormat>
        <label>IIP No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items - In Process</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/State_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Item_Update__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item - In Process</label>
        <referenceTo>Item_Update__c</referenceTo>
        <relationshipLabel>State Pricing</relationshipLabel>
        <relationshipName>State_Pricings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item - Active</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>State Pricing</relationshipLabel>
        <relationshipName>State_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State Pricing</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>State Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Pricings</pluralLabel>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_ItemUpdate_Trigger_Handler.cls
@isTest
private class Test_ItemUpdate_Trigger_Handler {
    
    @isTest static void test_method_one() {
        
        List<Item_Update__c> listItemUpdate = new List<Item_Update__c>();       

        User brandOwner = UtilitiesForTestMethodsClass.getUser('standarduser_test@silverlinecrm.com.sldev');
        List<sObject> customSettings = UtilitiesForTestMethodsClass.getCustomSetting();
        Item__c itemNew = UtilitiesForTestMethodsClass.getItemNew();
        State_Pricing__c statePricing = UtilitiesForTestMethodsClass.getStatePricing(itemNew.Id);

        Item_Update__c itemUpdate_copy = UtilitiesForTestMethodsClass.getItemUpdate('Item Update (Copy)', itemNew.Id);
        listItemUpdate.add(itemUpdate_copy);
        Item_Update__c itemUpdate_vintage_copy = UtilitiesForTestMethodsClass.getItemUpdate('New Item / Vintage (Copy)', itemNew.Id);
        listItemUpdate.add(itemUpdate_vintage_copy);
        Item_Update__c itemUpdate_unfinishedItem = UtilitiesForTestMethodsClass.getItemUpdate('Winery Unfinished Item (Copy)', itemNew.Id);
        listItemUpdate.add(itemUpdate_unfinishedItem);

        insert listItemUpdate;

        Test.StartTest();
            Item_Files__c itemFile = UtilitiesForTestMethodsClass.getItemFile(itemUpdate_copy.Id);
    
            itemUpdate_copy.Brand_Owner__c = brandOwner.Id;
            itemUpdate_copy.Item_designation__c = 'Winery only';
            itemUpdate_copy.Approval_Status__c = 'Completed - Record Locked';
    
            itemUpdate_vintage_copy.Approval_Status__c = 'Completed - Record Locked';
    
            itemUpdate_unfinishedItem.Approval_Status__c = 'Completed - Record Locked';
    
            statePricing.Item_Update__c = itemUpdate_copy.Id;
            update statePricing;
    
            UtilityTriggers.executedTriggers.remove('ItemUpdate_AfterUpdate');
            
            update listItemUpdate;
        Test.StopTest();
    }
        
}