objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Product_Description__c</fullName>
        <label>Marketing Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Product_Name__c</fullName>
        <description>Product name only, without brand or vintage information</description>
        <inlineHelpText>The &quot;name&quot; of the product only, WITHOUT the Brand name or varietal. For example, Chimney Rock Tomahawk Vineyard Cabernet 2013, the name would be &quot;Tomahawk Vineyard&quot;.</inlineHelpText>
        <label>Marketing Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Item - Active</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items - Active</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SL_Lightning_CompletenessIcon_Test.cls
@isTest
private class SL_Lightning_CompletenessIcon_Test {
    static testMethod void test() {
        Item__c i = new Item__c(Name='Test', Marketing_Product_Name__c='test' ,Marketing_Product_Description__c='test');
        insert i;
        System.debug(SL_Lightning_CompletenessIconController.getFieldCompletenessInfo(i.Id,'Item__c','Price_Info'));
        System.debug(SL_Lightning_CompletenessIconController.getPercentFieldMap(i.Id,'Item__c','Price_Info'));
        System.debug(SL_Lightning_CompletenessIconController.getPercentFieldMap(i.Id,'Item__c','Compliance_Required'));
        System.debug(SL_Lightning_CompletenessIconController.getPercentFieldMap(i.Id,'Item__c','Required_for_Operations_Approval'));
        System.debug(SL_Lightning_CompletenessIconController.getPercentFieldMap(i.Id,'Item__c','Required_for_Executive_Approval'));
        
        
    }
}