objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Base_Units_per_Case__c</fullName>
        <label>Base Units per Case</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Base_Units_per_Case</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IU_Type__c</fullName>
        <label>XXIU Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Item</fullName>
                </value>
                <value>
                    <fullName>New Item / Vintage (Copy)</fullName>
                </value>
                <value>
                    <fullName>Item Update (Copy)</fullName>
                </value>
                <value>
                    <fullName>Winery Unfinished Item</fullName>
                </value>
                <value>
                    <fullName>Winery Unfinished Item (Copy)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item - Active</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items - Active</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Item_Update__c.object
<CustomObject>
    <fields>
        <fullName>Base_Units_per_Case__c</fullName>
        <description>This is the total number of base units of product per case; even if there are kits or mini packs included. For example, Seven Daughters cans are 8 kits of 4 cans each per case, or 24 base units per case.</description>
        <inlineHelpText>This is the total number of base units of product per case; even if there are kits or mini packs included. For example, Seven Daughters cans are 8 kits of 4 cans each per case, or 24 base units per case.</inlineHelpText>
        <label>IIP: Base Units per Case</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Base_Units_per_Case</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IU_Type__c</fullName>
        <label>What would you like to do?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Item</fullName>
                </value>
                <value>
                    <fullName>New Item / Vintage (Copy)</fullName>
                </value>
                <value>
                    <fullName>Item Update (Copy)</fullName>
                </value>
                <value>
                    <fullName>Winery Unfinished Item</fullName>
                </value>
                <value>
                    <fullName>Winery Unfinished Item (Copy)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>What item do you want to copy from?</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipName>Item_Updates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item - In Process</label>
    <nameField>
        <displayFormat>IIP-{0}</displayFormat>
        <label>IIP No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items - In Process</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Base_Units_per_Case.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>1 item in the case</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>2 Pack</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>3 Pack</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>4 Pack</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>6 Pack</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12 Pack</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>12 Pack 1.5L</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24 Pack</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>9 Pack</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10 Pack</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15 Pack</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16 Pack</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20 Pack</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>36 Pack</label>
    </customValue>
    <customValue>
        <fullName>48</fullName>
        <label>48 Pack</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60 Pack</label>
    </customValue>
    <customValue>
        <fullName>96</fullName>
        <label>96 Pack</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>120 Pack</label>
    </customValue>
    <masterLabel>Base Units per Case</masterLabel>
</GlobalValueSet>

classes/Test_ValidationRecordLEX.cls
@isTest
private class Test_ValidationRecordLEX {
	
	@isTest static void test_method_one()
	{
		Item__c itemNew = new Item__c(
				Name = 'Item - Active TEST',
				Base_Units_per_Case__c = '12'

		);
		insert itemNew;

		Item_Update__c itemInProgress = new Item_Update__c(
				IU_Type__c = 'New Item',
				Base_Units_per_Case__c = '12'
		);
		insert itemInProgress;

		ValidationRecordLEX.provideInformationModal(itemInProgress.Id); 
	}
}