objects/Tours_and_Tastings__c.object
<CustomObject>
    <fields>
        <fullName>First_Visit_to_Napa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Visit to Napa?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Visit_to_Sonoma__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Visit to Sonoma?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Itinerary_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Itinerary Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Guests__c</fullName>
        <inlineHelpText>Number of Total Guest including Primary</inlineHelpText>
        <label>Number of Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>This is the type of person who is requesting a visit to the winery (ie. Distributor, Retailer, Consumer, etc.)</description>
        <inlineHelpText>This is the type of person who is requesting a visit to the winery (ie. Distributor, Retailer, Consumer, etc.)</inlineHelpText>
        <label>Primary Guest Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Distributor or Employee</fullName>
                </value>
                <value>
                    <fullName>Family and VIPs</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                    <label>On-Prem Retailer</label>
                </value>
                <value>
                    <fullName>Off-Prem Retailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour and Tasting Form</label>
    <nameField>
        <displayFormat>TT-{0}</displayFormat>
        <label>TT Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours and Tastings Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/controller_formatted_datetime_Test.cls
@isTest
private class controller_formatted_datetime_Test{
  @testSetup
  static void setupTestData(){
    test.startTest();
    Tours_and_Tastings__c tours_and_tastings_Obj = new Tours_and_Tastings__c(
            First_Visit_to_Napa__c = false,
            First_Visit_to_Sonoma__c = false,
            Itinerary_Approved__c = false,
            Number_of_Guests__c = 1,
            Request_Type__c = 'Consumer');
    Insert tours_and_tastings_Obj; 
    test.stopTest();
  }
  static testMethod void test_getFormattedDatetime_UseCase1(){
    List<Tours_and_Tastings__c> tours_and_tastings_Obj  =  [SELECT First_Visit_to_Napa__c,First_Visit_to_Sonoma__c,Itinerary_Approved__c from Tours_and_Tastings__c];
    System.assertEquals(true,tours_and_tastings_Obj.size()>0);
    controller_formatted_datetime obj01 = new controller_formatted_datetime();
    obj01.date_time = DateTime.now();
    obj01.getFormattedDatetime();
  }
}